#!/usr/bin/env python3
#
# This file is part of netpingd.
#
# netpingd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# netpingd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with netpingd.  If not, see <http://www.gnu.org/licenses/>.

# pylint: disable=broad-except
# pylint: disable=too-few-public-methods
# pylint: disable=no-self-use
# pylint: disable=invalid-name

"""Front end checking pings to evaluate the Warwick one-metre telescope network availability"""

import os
import re
import argparse
import datetime
import subprocess
import platform
import Pyro4

PYRO_CONFIG = {
    'nites'    : ('192.168.0.81', 9012, 'nites_netping_daemon'),
    'onemetre' : ('192.168.0.102', 9012, 'onemetre_netping_daemon')
    }

PING_TIMEOUT = 2
PING_REGEX = {
    'onemetre' : r'rtt min/avg/max/mdev = (?P<min>\d+\.\d+)/(?P<avg>\d+\.\d+)/' \
                 + r'(?P<max>\d+\.\d+)/(?P<mdev>\d+\.\d+) ms',
    'nites' : r'rtt Minimum = (?P<min>\d+\.\d+)ms, Maximum = (?P<max>\d+\.\d+)ms,' \
                 + r'Average = (?P<avg>\d+\.\d+)ms' 
    }

class NetworkPingDaemon:
    """Wraps a ping request to google and ngtshead"""
    def __init__(self, instrument):
        self._regex = re.compile(PING_REGEX[instrument])
        self.instrument = instrument

    def ping(self, address):
        """Ping an address and return the rtt time in milliseconds"""
        ping_str = "-n 1" if  platform.system().lower()=="windows" else "-c 1"
        output = subprocess.check_output("ping " + ping_str + " " + address)

        #if self.instrument == 'onemetre':
        #    output = subprocess.check_output([PYRO_CONFIG['/usr/bin/ping', '-c1', address],
        #                                      universal_newlines=True, timeout=PING_TIMEOUT)
        #else:
        #output = subprocess.check_output('C:\Windows\system32\ping.exe -n 1 -w {0} {1} '.format(
        #                                     PING_TIMEOUT*1000,address))
        
        # The last line of output (ignoring the final newline) contains the ping times
        times = output.split('\n')[-2]
        match = self._regex.match(times)
        if match is None:
            raise Exception('Failed to parse ping output: ' + output)

        return float(match.group('avg'))

    def last_measurement(self):
        """Query the latest valid measurement.
        May return None if no data is available"""
        try:
            return {
                'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
                'ngtshead': self.ping('ngtshead.warwick.ac.uk'),
                'google': self.ping('www.google.com'),
            }
        except Exception as exception:
            print('{} ERROR: failed to ping network: {}' \
                  .format(datetime.datetime.utcnow(), str(exception)))
            return None

def spawn_daemon(instrument):
    """Spawns the daemon and registers it with Pyro"""
    Pyro4.config.COMMTIMEOUT = 5

    pyro = Pyro4.Daemon(host=PYRO_CONFIG[instrument][0],
                        port=PYRO_CONFIG[instrument][1])
    netping = NetworkPingDaemon(instrument)
    uri = pyro.register(netping, objectId=PYRO_CONFIG[instrument][2])

    print('Starting Network ping daemon with Pyro ID:', uri)
    pyro.requestLoop()
    print('Stopping Network ping daemon with Pyro ID:', uri)

if __name__ == '__main__':
    description = 'Net Pinging Server'
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('instrument', choices=['onemetre', 'nites'], help='Select an instrument')
    args = parser.parse_args()
    spawn_daemon(args.instrument)

