#!/usr/bin/env python3.6
#
# This file is part of netpingd.
#
# netpingd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# netpingd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with netpingd.  If not, see <http://www.gnu.org/licenses/>.

"""Commandline client for querying the latest ping from google and ngtshead"""

# pylint: disable=invalid-name

import datetime
import json
import os
import sys
import Pyro4
from warwick.observatory.common import daemons

SCRIPT_NAME = os.path.basename(sys.argv[0])
sys.excepthook = Pyro4.util.excepthook

def format_ping(ms):
    """Formats a ping time for human-readable display"""
    if ms < 0:
        return '\033[91m\033[1mOFFLINE\033[0m'
    if ms < 10:
        return '\033[1m{:.0f} us\033[0m'.format(round(1000*ms))
    return '\033[1m{:.0f} ms\033[0m'.format(round(ms))

def print_status():
    """Prints the latest data in human-readable form"""
    latest = None
    try:
        with daemons.observatory_network_ping.connect() as netping:
            latest = netping.last_measurement()
    except Pyro4.errors.CommunicationError:
        print('error: unable to communicate with the network ping daemon')
        return 1

    if latest is not None:
        date = datetime.datetime.strptime(latest['date'], '%Y-%m-%dT%H:%M:%SZ')
        print('Data received \033[1m{}\033[0m:'.format(date))
        print('        External:')
        print('          Google: ' + format_ping(latest['google']))
        print('        NGTSHead: ' + format_ping(latest['ngtshead']))
        print('        Internal:')
        print('             W1m: ' + format_ping(latest['onemetre']))
        print('           NITES: ' + format_ping(latest['nites']))
        print('            GOTO: ' + format_ping(latest['goto']))
        print('           SWASP: ' + format_ping(latest['swasp']))
        print('             WHT: ' + format_ping(latest['swasp_gateway']))
    else:
        print('error: failed to query data')

    return 0

def print_json():
    """Prints the latest data in machine-readable form"""
    latest = None
    try:
        with daemons.observatory_network_ping.connect() as netping:
            latest = netping.last_measurement()
    except Pyro4.errors.CommunicationError:
        print('error: unable to communicate with the network ping daemon')
        return 1

    print(json.dumps(latest))

    return 0

def print_usage(name):
    """Prints the utility help"""
    print('Usage: {} <command>'.format(name))
    print()
    print('   status      print a human-readable summary of the ping times')
    print('   json        print a machine-readable summary of the ping times')
    print()

    return 1

if __name__ == '__main__':
    if len(sys.argv) == 1:
        sys.exit(print_usage(SCRIPT_NAME))

    if sys.argv[1] == 'status':
        sys.exit(print_status())
    elif sys.argv[1] == 'json':
        sys.exit(print_json())

    # Command not found
    sys.exit(print_usage(SCRIPT_NAME))
